<?xml version='1.0'?>
<robot name="experiment_box" xmlns:xacro="http://www.ros.org/wiki/xacro" >
  <xacro:property name="box_size" value="0.05" />
  <xacro:property name="box_mass" value="0.05" />
  <pose>0 0 ${box_size/2} 0 0 0</pose>
  <link name="experiemnt_box_link">
    <gravity>true</gravity>
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="${box_mass}" />
      <inertia
        ixx="${0.083*box_mass*2*box_size*box_size}"       
        ixy="0.0"
        ixz="0.0"
        iyy="${0.083*box_mass*2*box_size*box_size}"
        iyz="0.0"
        izz="${0.083*box_mass*2*box_size*box_size}"
      />
      <!-- for a box: ixx = 0.083 * mass * (y*y + z*z) -->
      <!-- for a box: ixy = 0 -->
      <!-- for a box: ixz = 0 -->
      <!-- for a box: iyy = 0.083 * mass * (x*x + z*z) -->
      <!-- for a box: iyz = 0 -->
      <!-- for a box: izz = 0.083 * mass * (x*x + y*y) -->
    </inertial>
    <collision name="collision">
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${box_size} ${box_size} ${box_size}" />
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${box_size} ${box_size} ${box_size}" />
      </geometry>
    </visual>
  </link>
  <gazebo reference="experiemnt_box_link">
    <material>Gazebo/Blue</material>
  </gazebo>  
</robot>
